# Generated by Django 3.2.10 on 2021-12-07 10:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_id', models.SmallIntegerField(verbose_name='İlçe ID')),
                ('ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
            ],
        ),
        migrations.CreateModel(
            name='Kapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_id', models.SmallIntegerField(verbose_name='İlçe ID')),
                ('mahalle_id', models.SmallIntegerField(verbose_name='Mahalle ID')),
                ('ilce_ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('mahalle_ad', models.CharField(max_length=50, verbose_name='Mahalle İsim')),
                ('kapi_no', models.CharField(max_length=50, verbose_name='Kapı No')),
                ('bina_ad', models.CharField(max_length=50, verbose_name='Bina İsmi')),
                ('yol_ad', models.CharField(max_length=250, verbose_name='Yol İsmi')),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
            ],
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_id', models.SmallIntegerField(verbose_name='İlçe ID')),
                ('mahalle_id', models.IntegerField(verbose_name='Mahalle ID')),
                ('ilce_ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
            ],
        ),
        migrations.CreateModel(
            name='Yol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_id', models.IntegerField(verbose_name='İlçe ID')),
                ('mahalle_id', models.IntegerField(verbose_name='Mahalle ID')),
                ('ilce_ad', models.CharField(max_length=50, verbose_name='İsim')),
                ('mahalle_ad', models.CharField(max_length=50, verbose_name='Mahalle İsim')),
                ('ad', models.CharField(max_length=250, verbose_name='İsim')),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
            ],
        ),
    ]
