# Generated by Django 3.2.10 on 2021-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211207_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapi',
            name='bina_ad',
            field=models.CharField(max_length=250, verbose_name='Bina İsmi'),
        ),
    ]
